#include "kernel/types.h"
#include "kernel/stat.h"
#include "kernel/fs.h"
#include "user/user.h"

// use recursion to allow find to descend into sub-dirs
// do not recurse into "." and ".."
// run make clean and then make qemu
// use C strings
// use strcmp() to compare strings

// find all the files in a dir tree with a specific name
// parameters: dir path, file name

/*
struct dirent{
  long d_ino;  // inode#
  off_t d_off; // dirent offset
  unsigned short d_reclen; // d_name length
  char d_name[NAME_MAX +1 ]; // filename or dirname
};

struct stat{
  int dev; // File system's disk device
  unit ino; // Inode#
  short type // file type
  short nlink; # of links to file
  unit64 size; // size of file (bytes)
};

// kernel/stat.h
#define T_DIR 1 // directory
#define T_FILE 2 // file
#define T_DEV 3 // device


int fstat(int fd, struct stat *buf);
fd: fd generated by open(2), etc.
buf: buffer to store file stat or info



*/

void find(char* path, char* filename){
  char buf[512];
  char* p;
  int fd;
  struct dirent de;
  struct stat st;
  
  if((fd = open(path, 0)) < 0){
    fprintf(2, "find: cannot open the file <%s>!\n", path);
    return; // not exit(1)?
  }

  if(fstat(fd,&st) < 0){
    fprintf(2, "find: cannot stat %s\n", path);
    close(fd);
    return;
  }

  if(strlen(path) + 1 + DIRSIZ+ 1 > sizeof(buf)){
    fprintf(2, "find:path too long\n");
    return;
  }
  strcpy(buf, path); // copy path to buf, but \0?
  p = buf + strlen(buf);
  *p++ = '/'; // using slash to separate parts

  while(read(fd, &de, sizeof(de)) == sizeof(de)){ // read return 0 or -1?
    
    //
    if(!de.inum) 
      continue;
    memmove(p, de.name, DIRSIZ);
    p[DIRSIZ] = 0;
    
    // cannot load file info
    if(stat(buf, &st) < 0){
      fprintf(2, "find: cannot stat %s\n", buf);
      continue;
    }

    // cannot recurse into '.' or '..'
    if(!strcmp(de.name, ".") || !(strcmp(de.name, "..")))
        continue;
     memmove(p, de.name, DIRSIZ);
     p[DIRSIZ] = 0;

    // needs to search all files in the dir-tree
    switch(st.type){
      case T_FILE:
        if(!strcmp(de.name, filename))
          printf("%s\n", buf);
       break;
      
      case T_DIR:
        find(buf, filename);
      
    /*
      case T_DEV:
        fprintf(2, "find: wrong file type!\n");
        break;
    */
    }    
  }
  close(fd);
}

int main(int argc, char* argv[]){
  if(argc == 1){
    fprintf(2, "Error: please check your input!\n");
    exit(1);
  }
  if(argc == 2){
    fprintf(2, "Error: no filename");
    exit(1);
  }
  find(argv[1], argv[2]);
  
  exit(0);
}
